puts "seeding users"
# u1 = User.create(username: "Babe", bio: "it me", password_digest: "beepboop")

puts "seeding bands"
b1 = Band.create(band_name: "Alcest", album: "Spiritual Instinct", genre: "Shoegaze/Black Metal", img: "https://www.metalkingdom.net/band/img/2019/06/956.jpg", bio: "Alcest is a French post-black metal band from Bagnols-sur-Cèze, founded and led by Neige (Stéphane Paut). It began in 2000 as a black metal solo project by Neige, soon a trio, but following the release of their first demo in 2001, band members Aegnor and Argoth left the band, leaving Neige as the sole member.In 2009 drummer Winterhalter from Les Discrets joined Alcest's line-up, after eight years with Neige as the sole full-time member. Since its creation, Alcest has released six studio albums and a number of EPs and split releases. Their fourth album, 2014's Shelter, marked a dramatic shift towards a distinctly shoegaze sound, however their subsequent album Kodama marked a return to their earlier blackgaze sound. The band are widely credited with pioneering the blackgaze/post-black metal genre, particularly through their EP Le Secret released in 2005.", player: "https://bandcamp.com/EmbeddedPlayer/album=1345717582/size=large/bgcol=333333/linkcol=e99708/tracklist=false/artwork=small/transparent=true/", player2: "https://bandcamp.com/EmbeddedPlayer/album=3672356025/size=large/bgcol=333333/linkcol=e99708/tracklist=false/artwork=small/transparent=true/", player3: "https://bandcamp.com/EmbeddedPlayer/album=2363589082/size=large/bgcol=333333/linkcol=e99708/tracklist=false/artwork=small/transparent=true/")

b2 = Band.create(band_name: "GAS", album: "Pop", genre: "Ambient", img: "https://f4.bcbits.com/img/a3083601247_10.jpg", bio: "GAS is the main musical project of German electronic musician and composer Wolfgang Voigt born 1961. The project was created as an expressive medium inspired by his experiences with taking LSD in the Königsforst, a German forest situated near his hometown of Cologne, for long periods in his youth. He has claimed that the intention of the project is to bring the forest to the disco, or vice-versa. Gas's music is primarily regarded as ambient techno and minimal techno, combining ambient music and 4/4 techno. It is the most abstract of Voigt's many projects, with albums consisting of several long untitled tracks. All Gas material shares a characteristic sound, based on a hazy ambient wash of drones and sampled loops, barely-audible fragments of horns, strings, record hiss and wind, usually accompanied by a four-on-the-floor kick drum.", player: "https://bandcamp.com/EmbeddedPlayer/album=810155818/size=large/bgcol=333333/linkcol=e99708/tracklist=false/artwork=small/transparent=true/", player2: "https://bandcamp.com/EmbeddedPlayer/album=2303878530/size=large/bgcol=333333/linkcol=e99708/tracklist=false/artwork=small/transparent=true/", player3: "https://bandcamp.com/EmbeddedPlayer/album=274940687/size=large/bgcol=333333/linkcol=e99708/tracklist=false/artwork=small/transparent=true/")

b3 = Band.create(band_name: "Giant Claw", album: "Orange Milk", genre: "Experimental/Electronic", img: "https://f4.bcbits.com/img/a1497928441_16.jpg", bio: "Artist Keith Rankin, from Columbus, Ohio is the co-owner of Orange Milk Records. He produces extensible digital art, as well as experimental music under the name Giant Claw.", player: "https://bandcamp.com/EmbeddedPlayer/album=1087983159/size=large/bgcol=333333/linkcol=e99708/tracklist=false/artwork=small/transparent=true/", player2: "https://bandcamp.com/EmbeddedPlayer/album=2036094323/size=large/bgcol=333333/linkcol=e99708/tracklist=false/artwork=small/transparent=true/", player3: "https://bandcamp.com/EmbeddedPlayer/album=2082484105/size=large/bgcol=333333/linkcol=e99708/tracklist=false/artwork=small/transparent=true/")

b4 = Band.create(band_name: "Kudzu", album: "Defeated", genre: "Post-Punk", img: "https://e.snmc.io/i/600/s/e067e0556d7a3b44b8b8f9a58d1a08b6/6767346/kudzu-defeated-Cover-Art.jpg", bio: "Kudzu is a synth-pop post-punk duo from Springfield, Missouri. Their catchy synth lines and memorable song writing make them an enjoyable group to listen to, and it never gets old.", player: "https://bandcamp.com/EmbeddedPlayer/album=1285405765/size=large/bgcol=333333/linkcol=e99708/tracklist=false/artwork=small/transparent=true/", player2: "https://bandcamp.com/EmbeddedPlayer/album=2903187256/size=large/bgcol=333333/linkcol=e99708/tracklist=false/artwork=small/transparent=true/", player3: "https://bandcamp.com/EmbeddedPlayer/album=1872494523/size=large/bgcol=333333/linkcol=e99708/tracklist=false/artwork=small/transparent=true/" )

b5 = Band.create(band_name: "Mastodon", album: "Remission", genre: "Heavy Metal", img: "https://upload.wikimedia.org/wikipedia/en/4/47/Mastodonremission.jpg", bio: "Mastodon is an American heavy metal band from Atlanta, Georgia, formed in 2000. They are quoted as one of the preeminent metal acts of the early 21st century.", player: "https://bandcamp.com/EmbeddedPlayer/album=3267479739/size=large/bgcol=333333/linkcol=e99708/artwork=small/transparent=true/", player2: "https://bandcamp.com/EmbeddedPlayer/album=105533117/size=large/bgcol=333333/linkcol=e99708/tracklist=false/artwork=small/transparent=true/", player3: "https://bandcamp.com/EmbeddedPlayer/album=3602351605/size=large/bgcol=333333/linkcol=e99708/tracklist=false/artwork=small/transparent=true/")

b6 = Band.create(band_name: "Rendez Vous", album: "Distance", genre: "Post-Punk", img: "https://f4.bcbits.com/img/a3592202202_10.jpg", bio: "Rendez Vous is a post-punk/new-wave band from Paris. They were founded in 2012 by Francis Mallari and Elliot Bethault. A few months later, they added Maxime Gendre and Simon Dubourg. The band released their first EP in 2014, Rendez-Vous, for Zappruder Records. The band start touring across Europe in the summer of 2015.", player: "https://bandcamp.com/EmbeddedPlayer/album=4083508719/size=large/bgcol=333333/linkcol=e99708/tracklist=false/artwork=small/transparent=true/", player2: "https://bandcamp.com/EmbeddedPlayer/album=3534909906/size=large/bgcol=333333/linkcol=e99708/tracklist=false/artwork=small/track=522519929/transparent=true/", player3: "https://bandcamp.com/EmbeddedPlayer/album=3916666291/size=large/bgcol=333333/linkcol=e99708/tracklist=false/artwork=small/transparent=true/")

b7 = Band.create(band_name: "Retail", album: "Dead", genre: "Punk", img: "https://s3.amazonaws.com/assets.imposemagazine.com/wp-content/uploads/2016/11/a2738897911_10.jpg", bio: "Self-proclaimed 'sons of Brooklyn', Retail are an energetic local punk unit that bring style and passion to their live performances. This is fun dancing music.", player: "https://bandcamp.com/EmbeddedPlayer/album=4229945759/size=large/bgcol=333333/linkcol=e99708/tracklist=false/artwork=small/transparent=true/", player2: "https://bandcamp.com/EmbeddedPlayer/album=1630100310/size=large/bgcol=333333/linkcol=e99708/tracklist=false/artwork=small/transparent=true/", player3: "https://bandcamp.com/EmbeddedPlayer/album=1995999120/size=large/bgcol=333333/linkcol=e99708/tracklist=false/artwork=small/transparent=true/")

b8 = Band.create(band_name: "SHXCXCHCXSH", album: "Linear S Decoded", genre: "Ambient/Experimental", img: "https://lastfm.freetls.fastly.net/i/u/770x0/1d8ffff7ba7b1af51015ba28335f7c81.jpg", bio: "SHXCHXCHXSH has became synonymous to haunting and abstract experimental techno. With the intricate balance between light and dark as well as the realms of drone, noise and techno their productions must be described as versatile and broad.", player: "https://bandcamp.com/EmbeddedPlayer/album=939909594/size=large/bgcol=333333/linkcol=e99708/tracklist=false/artwork=small/transparent=true/", player2: "https://bandcamp.com/EmbeddedPlayer/album=831159148/size=large/bgcol=333333/linkcol=e99708/tracklist=false/artwork=small/transparent=true/", player3: "https://bandcamp.com/EmbeddedPlayer/album=1527524915/size=large/bgcol=333333/linkcol=e99708/tracklist=false/artwork=small/transparent=true/")

b9 = Band.create(band_name: "Sweet Trip", album: "A Tiny House, In Secret Speeches, Polar Equals", genre: "Shoegaze", img: "https://cdn.shopify.com/s/files/1/0961/0594/products/DRL362-1B_Val_Sits_3000pix_RGB.jpg?v=1619644150", bio: "Sweet Trip is an electronic/experimental rock act formed in 1993 in the Bay Area of California, United States, currently consisting of musician Roberto Burgos. They are known for their dreamy soundscapes and dense production techniques, often blending alternative rock subgenres with intelligent dance music.", player: "https://bandcamp.com/EmbeddedPlayer/album=215652981/size=large/bgcol=333333/linkcol=e99708/tracklist=false/artwork=small/transparent=true/", player2: "https://bandcamp.com/EmbeddedPlayer/album=432659920/size=large/bgcol=333333/linkcol=e99708/tracklist=false/artwork=small/transparent=true/", player3: "https://bandcamp.com/EmbeddedPlayer/album=3786395281/size=large/bgcol=333333/linkcol=e99708/tracklist=false/artwork=small/transparent=true/")

b10 = Band.create(band_name: "Warthog", album: "Warthog", genre: "Hardcore Punk", img: "https://f4.bcbits.com/img/a1029186125_10.jpg", bio: "Warthog don't do albums. Since their 2012 formation, the New York band — which comprises former Men bassist Chris Hansell, plus members of Nude Beach, Dawn of Humans, Creem and Nomos — have abided by one of hardcore's most sacrosanct principles: Keep the releases coming, but keep them short, loud and filler-free.", player: "https://bandcamp.com/EmbeddedPlayer/album=3041566802/size=large/bgcol=333333/linkcol=e99708/tracklist=false/artwork=small/transparent=true/", player2: "https://bandcamp.com/EmbeddedPlayer/album=1164381289/size=large/bgcol=333333/linkcol=e99708/tracklist=false/artwork=small/transparent=true/", player3: "https://bandcamp.com/EmbeddedPlayer/album=1413112296/size=large/bgcol=333333/linkcol=e99708/tracklist=false/artwork=small/transparent=true/")

puts "seeding reviews"
# review1=Review.create(title: "Good Album", description: "I really enjoy this album", user_id: u1.id, band_id: b1.id)

puts "done seeding!"
